apiVersion: v1
kind: Pod
metadata: 
  name: test-ed
spec:
  containers:
    - image: nginx
      name: test-ed
      volumeMounts:
      - name: vol-cache
        mountPath: /cache
  volumes:
    - name: vol-cache
      emptyDir: {}

